services:
  smartphone-robot-build-env:
    build:
      context: .
    image: topher217/smartphone-robot-firmware:latest
    container_name: smartphone-robot-firmware
    volumes:
      - ../:/project
    working_dir: /project
    devices:
      - /dev/ttyACM0:/dev/ttyACM0:rwm
      - /tmp/pico-probe:/dev/pico-probe:rwm
    ports:
      - "4444:4444"
      - "6666:6666"
      - "3333:3333"
      - "3334:3334"
