services:
  smartphone-robot-build-env:
    build:
      context: .
    image: topher217/smartphone-robot-firmware:latest
    container_name: smartphone-robot-firmware
    volumes:
      - ../:/project
    working_dir: /project
    devices:
      - /dev/ttyACM0:/dev/ttyACM0:rwm
      - /dev/bus/usb/003/009:/dev/bus/usb/003/009:rwm
    ports:
      - "4444:4444"
      - "6666:6666"
