name: PR Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: lukstep/raspberry-pi-pico-sdk:v0.0.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build
        run: ./b.sh
